    %% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\zainq\Google Drive\Spring 2017\Data Mining\assignment1\Task4\winequality-red.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/18 22:43:38

%% Initialize variables.
filename = 'C:\Users\zainq\Google Drive\Spring 2017\Data Mining\assignment1\Task4\winequality-red.csv';
delimiter = ';';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
fixedacidity = dataArray{:, 1};
volatileacidity = dataArray{:, 2};
citricacid = dataArray{:, 3};
residualsugar = dataArray{:, 4};
chlorides = dataArray{:, 5};
freesulfurdioxide = dataArray{:, 6};
totalsulfurdioxide = dataArray{:, 7};
density = dataArray{:, 8};
pH = dataArray{:, 9};
sulphates = dataArray{:, 10};
alcohol = dataArray{:, 11};
quality = dataArray{:, 12};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;